# -*- coding: utf-8 -*-
"""movie_reviews.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IUUdROBbh3fpn-_D67Pg9qzFsBFNbVAM
"""

import requests
from bs4 import BeautifulSoup
import time
import csv

need_reviews_cnt = 100
reviews = []
review_data=[]

for page in range(15):
    url = f'https://movie.naver.com/movie/point/af/list.naver?&page={page}'
    html = requests.get(url)
    soup = BeautifulSoup(html.content,'html.parser')
    reviews = soup.find_all("td",{"class":"title"})


print(reviews)